<?php

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\my_team_member\Entity\TeamMember;

/**
 * Implements hook_entity_type_build().
 */
function my_team_member_entity_type_build(EntityTypeManagerInterface $entity_type_manager) {
  $entity_type = $entity_type_manager->getDefinition('node');
  $entity_type->addBundle('team_member');
}

/**
 * Implements hook_entity_base_field_info().
 */
function my_team_member_entity_base_field_info($entity_type) {
  if ($entity_type->id() === 'node') {
    return []; // Field definitions are already defined in the TeamMember class
  }
}

